INSERT INTO ACCOUNT(ID,FIRSTNAME,SURNAME,ACCNO) VALUES(1,'John','Doe','1234')
INSERT INTO ACCOUNT(ID,FIRSTNAME,SURNAME,ACCNO) VALUES(2,'Jane','Doe','1235')
INSERT INTO ACCOUNT(ID,FIRSTNAME,SURNAME,ACCNO) VALUES(3,'Jim','Taylor','1236')
INSERT INTO TRANSACTION(ID,NAME,ACCOUNT_ID) VALUES(1,'ABC',2)